# Logistic Regression


In [68]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [69]:
data = pd.read_csv(r'C:\Users\Asus\Desktop\Machine Learning Workshop 20\Social_Network_Ads.csv')

In [70]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [71]:
age = data.iloc[:,1:-1].values
purchase = data.iloc[:,-1].values

In [72]:
from sklearn.preprocessing import LabelEncoder
lEncoder = LabelEncoder()
age[:,0] = lEncoder.fit_transform(age[:,0])

In [73]:
from sklearn.preprocessing import StandardScaler
sScaler = StandardScaler()
age_scaled = sScaler.fit_transform(age)

In [74]:
age[1,:]

array([1, 35, 20000], dtype=object)

In [75]:
age_scaled[1,:]

array([ 1.02020406, -0.25358736, -1.46068138])

In [76]:
from sklearn.model_selection import train_test_split      #returns 4 parameters i.e. x_train, x_test, y_train, y_test
x_train, x_test, y_train, y_test = train_test_split(age_scaled,purchase,test_size = 0.2)       #random test split of 20%

In [77]:
from sklearn.linear_model import LogisticRegression
classifer = LogisticRegression()

In [78]:
classifer.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [79]:
y_pred = classifer.predict(x_test)

In [80]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [81]:
cm

array([[46,  3],
       [ 8, 23]], dtype=int64)

In [82]:
classifer.score(x_test,y_test)

0.8625