# Multiple Linear Regression

In [40]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [41]:
data = pd.read_csv(r'C:\Users\Asus\Desktop\Machine Learning Workshop 20\50_Startups.csv')

In [42]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [43]:
x = data.iloc[:,:-1].values
x.shape

(50, 4)

In [44]:
y = data.iloc[:,-1].values
y.shape

(50,)

In [45]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
lEncoder = LabelEncoder()
ohEncoder = OneHotEncoder()

In [46]:
lEncoder.fit(x[:,3])

LabelEncoder()

In [47]:
lEncoder.classes_

array(['California', 'Florida', 'New York'], dtype=object)

In [48]:
x[1,:]

array([162597.7, 151377.59, 443898.53, 'California'], dtype=object)

In [49]:
x[:,3] = lEncoder.transform(x[:,3])
x[1,:]

array([162597.7, 151377.59, 443898.53, 0], dtype=object)

In [50]:
X = ohEncoder.fit_transform(x[:,[3]]).toarray()

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [51]:
X[1,:]

array([1., 0., 0.])

In [52]:
x.shape

(50, 4)

In [53]:
x[0,:]

array([165349.2, 136897.8, 471784.1, 2], dtype=object)

In [54]:
x = x[:,:-1]

In [55]:
x.shape

(50, 3)

In [56]:
X.shape

(50, 3)

In [57]:
x_new = np.concatenate((x,X),axis=1)
x_new.shape

(50, 6)

In [58]:
x_new

array([[165349.2, 136897.8, 471784.1, 0.0, 0.0, 1.0],
       [162597.7, 151377.59, 443898.53, 1.0, 0.0, 0.0],
       [153441.51, 101145.55, 407934.54, 0.0, 1.0, 0.0],
       [144372.41, 118671.85, 383199.62, 0.0, 0.0, 1.0],
       [142107.34, 91391.77, 366168.42, 0.0, 1.0, 0.0],
       [131876.9, 99814.71, 362861.36, 0.0, 0.0, 1.0],
       [134615.46, 147198.87, 127716.82, 1.0, 0.0, 0.0],
       [130298.13, 145530.06, 323876.68, 0.0, 1.0, 0.0],
       [120542.52, 148718.95, 311613.29, 0.0, 0.0, 1.0],
       [123334.88, 108679.17, 304981.62, 1.0, 0.0, 0.0],
       [101913.08, 110594.11, 229160.95, 0.0, 1.0, 0.0],
       [100671.96, 91790.61, 249744.55, 1.0, 0.0, 0.0],
       [93863.75, 127320.38, 249839.44, 0.0, 1.0, 0.0],
       [91992.39, 135495.07, 252664.93, 1.0, 0.0, 0.0],
       [119943.24, 156547.42, 256512.92, 0.0, 1.0, 0.0],
       [114523.61, 122616.84, 261776.23, 0.0, 0.0, 1.0],
       [78013.11, 121597.55, 264346.06, 1.0, 0.0, 0.0],
       [94657.16, 145077.58, 282574.31, 0.

In [59]:
x_new = x_new[:,:-1]
x_new.shape

(50, 5)

In [60]:
from sklearn.model_selection import train_test_split      #returns 4 parameters i.e. x_train, x_test, y_train, y_test
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)       #random test split of 20%

In [61]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()

In [62]:
mlr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [63]:
mlr.intercept_

46090.95276228324

In [64]:
mlr.coef_

array([ 0.81991688, -0.00811043,  0.02956469])

In [73]:
y_pred = mlr.predict(x_test)
y_pred

array([ 73136.31438024, 150748.49942869, 114732.06204179, 159046.50378365,
       135272.75219765, 102259.39094861, 116519.19090759, 174831.02873343,
        45960.41327321, 164137.39418007])

In [70]:
y_test

array([ 77798.83, 132602.65, 110352.25, 156122.51, 144259.4 , 103282.38,
       118474.03, 182901.99,  64926.08, 156991.12])