# Using Numpy Package

In [5]:
import numpy as np
b = [1,2,3,4,5]

In [6]:
print(b)
type(b)

[1, 2, 3, 4, 5]


list

In [4]:
c = np.array(b)
print(c)
type(c)

[1 2 3 4 5]


numpy.ndarray

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
%timeit np.arange(0,11)**2

1.31 µs ± 27.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
c.ndim

1

In [12]:
c.shape

(5,)

In [14]:
e = [[1,2,3],[3,4,5],[7,4,3]]
print(e)

[[1, 2, 3], [3, 4, 5], [7, 4, 3]]


In [16]:
f = np.array(e)
print(f)

[[1 2 3]
 [3 4 5]
 [7 4 3]]


In [17]:
f.ndim

2

In [18]:
f.shape

(3, 3)

In [20]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.random.rand(3,2)

array([[0.56103966, 0.32617251],
       [0.86761655, 0.89722048],
       [0.22303289, 0.81946365]])